version: '3'
services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
      - db:/var/lib/mysql:delegated
    command: mysqld --max_allowed_packet=16M --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  db:
networks:
  goukon:
    external: true
